default:
    @just --list

clean:
    -test -e .out && rm -r .out
    mkdir .out

purge: clean
    cargo clean

build: clean
    mkdir .out/bin
    mkdir .out/sbin

    cargo build -r

    awk '{system("cp target/release/" $1 " .out/bin")}'   modules_bin.txt
    awk '{system("cp target/release/" $1 " .out/sbin")}'  modules_sbin.txt
