site_name: Oxide Linux
docs_dir: spec

theme:
  name: readthedocs
  hljs_languages:
    - rust

nav:
  - Home: index.md
  - Compatibility: compat.md
  - Quartz:
      - Overview: quartz/overview.md
      - System Unit: quartz/system_unit.md
  - Filesystem Standard:
      - Overview: fs/overview.md
  - About:
      - License: license.md
