site_name: Oxide Linux
docs_dir: spec

theme:
  name: readthedocs
  hljs_languages:
    - rust

nav:
  - Home: index.md
  - Compatibility: compat.md
  - Getting Started:
      - Installation: tutorial/install.md
      - Setting Up: tutorial/setup.md
  - Quartz:
      - Overview: quartz/overview.md
  - Filesystem Standard:
      - Overview: fs/overview.md
  - About:
      - License: license.md
