default:
    @just --list

clean:
    -test -e .out && rm -r .out
    mkdir .out

purge: clean
    cargo clean

build: clean
    mkdir .out/bin

    cargo build -r

    awk '{system("cp target/release/" $1 " .out/bin")}'  binaries.txt
